from paramiko import SSHClient, AutoAddPolicy
client = SSHClient()
client.set_missing_host_key_policy(AutoAddPolicy())
client.save_host_keys('D:\\id_rsa.pub')
client.connect(hostname='192.168.222.131', username='root', password='me')
# print(client.get_host_keys().values()[0])
# stdin, stdout, stderr = client.exec_command('find / -name {}'.format('authorized_keys'))
# out = stdout.read().decode()
# err = stderr.read().decode()
# if not out:
#     print('Got here')
#     client.exec_command('mkdir -p ~/.ssh/ && touch ~/.ssh/{}'.format('authorized_keys'))
#     stdin, stdout, stderr = client.exec_command('find / -name {}'.format('authorized_keys'))
#     out = stdout.read().decode()
#     err = stderr.read().decode()
# print(out)
# print(err)