cli = ""                # Params
password = ""           # Password
dirs = ""               # Sincable folders
files = ""              # Sincable files
user = ""               # User name
port = ""               # Port (if needed)
host = ""               # Host name
dist = ""               # Distenation folder
pass_file = ""          # Password file
